server:
  port: 8080
  context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: triumphant%wangkai
    password: end1pgdn3Q.
    url: jdbc:mysql://triumphant.mysqldb.chinacloudapi.cn/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null


#logging:
#  pattern:
#    #%d 日期 %msg信息 %n换行
#    console: "%d - %msg%n"
#  path: D:\log\tomcat
#  file: D:\log\tomcat\sell.log
#  level:
#    com.pluto.sell.service.impl.OrderServiceImplTest: debug